### ISSUE TITLE
logging to syslog does not work

### ISSUE THREAD

**Issue by checkmypi** [elastic/logstash-forwarder#279] opened 2014-10-06 11:03 UTC
Hello,
Logging to syslog does not work for me. 
I suspect this is something to do with 
func emit() 
and the fact that infolog is used instead of log ( which is where syslog output is configured ) 
but I'm not familiar with go enough to provide a patch.

**Comment by cybervedaa** [comment] 2015-01-05 19:06
+1
Im having the same issue too on centos. Correct me if im wrong, but the log messages are supposed to show up in /var/log/messages right?
syslog is running with the default syslog.conf

**Comment by DanielRedOak** [comment] 2015-01-29 15:45
I haven't tested yet (but will), but this might be fixed in #337 which seems to have been merged into master

**Comment by tbragin** [comment] 2015-07-31 17:53
Duplicate of https://github.com/elastic/logstash-forwarder/issues/137

**Closed by tbragin** 2015-07-31 17:53 UTC
