### ISSUE TITLE
Logstash Forwarder Keeps Rotated Files Open

### ISSUE THREAD

**Issue by clutchbeyers** [elastic/logstash-forwarder#541] opened 2015-10-30 16:53 UTC
We are running logstash-forwarder-0.4.0-1 on our RHEL 7 Linus hosts and we noticed logstash will continue to hold on to the deleted logrotate files until logstash-forwarder service gets restarted. Right now I have a cron job that will do that restart, but that is over-head we are hoping to eliminate considering the potential for race conditions to occur not on our watch. I know there have been issues opened on this very subject, but no solution. Even with the "dead time" altered or using 24h defaults, it does not release those rotated logs that should have fallen off via logrotate....causing /var to fill up over time.

When I run ls -lh on /proc/XXX/fd, it shows which file handlers logstash has open and you will see (deleted) files in there.

Looking to get the dialogue going on this to see if I missed a updated LSF.

**Comment by jordansissel** [comment] 2015-10-30 17:11
This is by design because some logrotation mechanisms are broken and if we do not keep the files watched for a short period of time after rotation, data can be lost.

As you found, logstash-forwarder has a setting called "dead time" (default is 24 hours, I think). This setting determines how long after the last write that a file is considered dead. I don't remember any recent bugs that cause this dead time to not be acted on, and many other users seem to report it working successfully.

Can you link to your logstash-forwarder config as well as the `ls -lh /proc/XYZ/fd` (or `lsof -nPp /proc/XYZ/fd`) output when it's got deleted files? Also, if possible, showing the current time `date` and the last modified-time of each deleted file (`stat -L /proc/XYZ/fd/N` where N is the fd of a deleted file)

**Comment by clutchbeyers** [comment] 2015-10-30 17:59
I will get the rest of the output to you, I put more aggression on when logs get rotated and already have some log files marked as deleted that it is still holding on to. But I want to give it a day to meet the 24 hour default dead time and prove that it hasnt been modified since then. Thanks!

'{
  # The network section covers network configuration :)
  "network": {
    "servers": [ "10.63.220.124:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
    # A list of downstream servers listening for our messages.
    # logstash-forwarder will pick one at random and only switch if
    # the selected one appears to be dead or unresponsive
    #"servers": [ "localhost:5043" ],

    # The path to your client ssl certificate (optional)
    #"ssl certificate": "./logstash-forwarder.crt",
    # The path to your client ssl key (optional)
    #"ssl key": "./logstash-forwarder.key",

    # The path to your trusted ssl CA file. This is used
    # to authenticate your downstream server.
    #"ssl ca": "./logstash-forwarder.crt",

    # Network timeout in seconds. This is most important for
    # logstash-forwarder determining whether to stop waiting for an
    # acknowledgement from the downstream server. If an timeout is reached,
    # logstash-forwarder will assume the connection or server is bad and
    # will connect to a server chosen at random from the servers list.
    #"timeout": 15
  },
 # The list of files configurations
"files": [
   {
      "paths": [
        "/var/log/nova/*.log"
       ],
      "fields": { "type": "nova" }
    },
    {
      "paths": [
        "/var/log/neutron/*.log"
       ],
      "fields": { "type": "neutron" }
    },
    {
      "paths": [
        "/var/log/cinder/*.log"
       ],
      "fields": { "type": "cinder" }
    },
    {
      "paths": [
        "/var/log/glance/*.log"
       ],
      "fields": { "type": "glance" }
    },
    {
      "paths": [
        "/var/log/heat/*.log"
       ],
      "fields": { "type": "heat" }
    },
    {
      "paths": [
        "/var/log/httpd/*.log"
       ],
      "fields": { "type": "http" }
    },
    {
      "paths": [
        "/var/log/horizon/*.log"
       ],
      "fields": { "type": "horizon" }
    },
    {
      "paths": [
        "/var/log/keystone/*.log"
       ],
      "fields": { "type": "keystone" }
    },
    {
      "paths": [
        "/var/log/mariadb/*.log"
       ],
      "fields": { "type": "mariadb" }
    },
    {
      "paths": [
        "/var/log/messages"
       ],
      "fields": { "type": "syslog" }
    },
    {
      "paths": [
        "/var/log/mongodb/*.log"
       ],
      "fields": { "type": "mongodb" }
    },
    {
      "paths": [
        "/var/log/openvswitch/*.log"
       ],
      "fields": { "type": "openvswitch" }
    },
    {
      "paths": [
        "/var/log/pacemaker.log"
       ],
      "fields": { "type": "pacemaker" }
    },
    {
      "paths": [
        "/var/log/datadog/*.log"
       ],
      "fields": { "type": "datadog" }
    },
    {
      "paths": [
        "/var/log/ceilometer/*.log"
       ],
      "fields": { "type": "ceilometer" }
    },
    {
      "paths": [
        "/var/log/cron"
       ],
      "fields": { "type": "cron" }
    },
    {
      "paths": [
        "/var/log/centrify_mapper_error.log"
       ],
      "fields": { "type": "centrify" }
    },
    {
      "paths": [
        "/var/log/rabbitmq/*.log-2*"
       ],
      "fields": { "type": "rabbit" }
    }
  ]
}'

**Comment by jordansissel** [comment] 2015-10-30 18:12
@clutchbeyers if you need to keep things stable, you can keep bouncing logstash-forwarder, just make the dead-time shorter than your restart interval and try to observe LSF before it bounces and after a rotation? Either way, thanks for helping provide some details here so we can hopefully get to the bottom of this problem :)

**Comment by ruflin** [comment] 2015-12-01 13:04
@clutchbeyers I think we have this now solved by introducing force_close_files config in filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_force_close_files

**Comment by ruflin** [comment] 2016-03-01 10:05
Closing as all further development is done in filebeat https://github.com/elastic/beats/tree/master/filebeat

**Closed by ruflin** 2016-03-01 10:05 UTC
