### ISSUE TITLE
Unhandled exception 'Unknown frame type'

### ISSUE THREAD

**Issue by tthef** [elastic/logstash-forwarder#255] opened 2014-08-27 13:44 UTC
When something that does not talk the lumberjack protocol tries to connect on the lumberjack port, the lubmerjack listener crashes. For exemaple, when the port is hit by the openvas scanner you get:

RuntimeError: Unknown frame type: 69
  header at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:142

This should be handled more gracefully, I think.

**Comment by mzimmerman** [comment] 2015-01-08 16:33
Welp, that explains why my service keeps crashing after a Nessus scan!  This is a fragile service.

**Comment by jordansissel** [comment] 2015-01-08 19:41
>  This is a fragile service.

Not intentionally.

**Comment by ssoroka-se** [comment] 2015-02-03 22:10
Clearly the server should not be raising exceptions for poorly formatted requests!

**Comment by jordansissel** [comment] 2015-02-04 01:26
@ssoroka-se if only computers were that simple :)

**Comment by jordansissel** [comment] 2015-02-04 01:27
For folks hitting this, please know that we know about this bug, have reproduced it, and will be fixing it soon. Intention is to include the fix in Logstash 1.5.0

**Comment by leaskim** [comment] 2015-03-30 08:44
Hello, any news on this bug ? Using NXLog to send logs from a Windows 2008 server make my logstash crash, "unknown frame type: 48". Thanks,

**Comment by jayeshpise** [comment] 2015-04-06 23:45
Guys, since the 1.5.0 rc is out, is this bug fixed in there ?

**Comment by jordansissel** [comment] 2015-08-10 18:12
Fixed recently.

**Comment by ph** [comment] 2015-08-10 18:13
Fixed in https://github.com/logstash-plugins/logstash-input-lumberjack/pull/8

**Closed by jordansissel** 2015-08-10 18:12 UTC
Labels: bug
