### ISSUE TITLE
logstash forwarder linux 64bit does not work

### ISSUE THREAD

**Issue by odq773git** [elastic/logstash-forwarder#433] opened 2015-03-27 20:53 UTC
THe installable that is on https://www.elastic.co/downloads/logstash for linux 64-bit for logstash forwarder 0.4.0 does not work

**Comment by knalli** [comment] 2015-04-14 13:15
@odq773git  I'm using this, it works for me on RHEL/Ami. Perhaps you should add more details what exactly is going wrong along some specs about your environment.

**Comment by paweldolecinski** [comment] 2015-07-22 14:21
I can confirm that it does not work under busybox:
I'm trying to run it in from docker image
$ docker run -it --rm busybox 
# wget download.elastic.co/logstash-forwarder/binaries/logstash-forwarder_linux_amd64 -O logstash-forwarder
# /logstash-forwarder 
/bin/sh: /logstash-forwarder: not found

With 32bit version everything works;
Busybox is 64-bit
# uname -a
Linux 710038b45f5a 3.16.0-28-generic #38-Ubuntu SMP Sat Dec 13 16:13:28 UTC 2014 x86_64 GNU/Linu

**Comment by ruflin** [comment] 2015-10-05 12:08
@paweldolecinski I just tried your lines above with the master of filebeat (the next version of logstash-forwarder). It seems like amd64 now works as expected. https://github.com/elastic/filebeat

**Comment by ruflin** [comment] 2015-10-07 12:05
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.

**Closed by ruflin** 2015-10-07 12:05 UTC
Labels: filebeat, need more information
