### ISSUE TITLE
Bug in logstash-forwarder_linux_386

### ISSUE THREAD

**Issue by Yzord** [elastic/logstash-forwarder#441] opened 2015-04-20 12:37 UTC
I think i have found a bug in the logstash-forwarder i386 version.

In my logstash-forwarder config i use an IP for the LS server, but when i execute logstash-forwarder it thinks it is an hostname.

2015/04/20 14:26:32.674411 DNS lookup failure "1.2.3.4": lookup 1.2.3.4: invalid domain name

All my other clients (64bits) are working ok, only the 32bits clients are doing this. Is there a way around so that it thinks it is an IP?

**Comment by magnusbaeck** [comment] 2015-04-20 19:05
This looks like a duplicate of #371.

**Comment by Yzord** [comment] 2015-04-20 20:40
Yup, it looks like it...glad that it is recognized as a bug :)

**Comment by torrancew** [comment] 2015-04-20 21:34
@Yzord if it's definitely the same error, could you close this one and note in #371 that you're impacted by it?

**Closed** 2015-04-21 07:43 UTC
