### ISSUE TITLE
Building logstash forwarder for MIPS platform

### ISSUE THREAD

**Issue by stevecalvert** [elastic/logstash-forwarder#539] opened 2015-10-13 14:52 UTC
I saw your recommendations about not using gccgo to build logstash-forwarder, but I'm persevering since I'm not aware of any other means of getting the forwarder onto a MIPS target.  I've managed to build gccgo and I'm able to build/run a single file example .go app on the target albeit with static linking to get around some glibc incompatibilities

So far so good, but I've come unstuck trying to rebuild logstash-forwarder for MIPS.  Based on the readme instructions, I can build for Linux using

    go build -o logstash-forwarder 

and that works fine, but I get compile errors (subset included below) when I try to build for MIPS from the logstash-forwarder folder:-

     gccgo -g -o lgf `ls *.go`

fileinfo_linux.go:8:1: error: redefinition of ‘file_ids’
 func file_ids(info *os.FileInfo) (uint64, uint64) {
 ^
fileinfo_darwin.go:8:1: note: previous definition of ‘file_ids’ was here
 func file_ids(info *os.FileInfo) (uint64, int32) {
 ^
fileinfo_darwin.go:10:26: error: incompatible type for return value 2 (cannot use type uint32 as type int32)
   return fstat.Ino, fstat.Dev

filecompare.go:12:49: error: incompatible types in binary expression
   return (fstat.Ino == state.Inode && fstat.Dev == state.Device)
                                                 ^
Any ideas?

**Comment by stevecalvert** [comment] 2015-10-13 15:04
I should have mentioned, I also tried building using the following, but that gave me an error I am still trying to make sense of...
```
go build -o lgf -compiler gccgo .
# _/home/centos/logstash-forwarder
gccgo: error: unrecognized command line option ‘-m64’
```

**Comment by jordansissel** [comment] 2015-10-13 15:38
I've never used gccgo, so I can't offer much help there.

```
fileinfo_linux.go:8:1: error: redefinition of ‘file_ids’
fileinfo_darwin.go:8:1: note: previous definition of ‘file_ids’ was here
```

The normal Go compiler uses these files (ending in `_` plus the platform name, such as linux or darwin) as a special hint to only compile on those specific platforms. This allows Go programs to provide alternate implementations of something on a per-platform basis. This is similar to C's `#ifdef`-style of doing something like `#ifdef LINUX` (or something) but is switched per-file, not with compiler conditionals within a single file.

Your command: gccgo -g -o lgf `ls *.go`

The problem is that you are passing all files to the compiler, so you are providing both fileinfo_linux.go and fileinfo_darwin.go, and you get a conflict.

Beyond that, not sure what to suggest.

**Comment by ruflin** [comment] 2015-10-14 00:01
@stevecalvert Can you try to compile filebeat as this will be the future version of logstash-forwarder? https://github.com/elastic/filebeat/ We handle the file_ids a little bit different, so it could work.

**Comment by stevecalvert** [comment] 2015-10-14 10:27
@ruflin thanks for responding - I've extracted the filebeat codebase, but without the dependency tools in my MIPS environment. I'm just guessing at which .go source files to use and ending up with a myriad of compile errors.
```
go get github.com/tools/godep
2015/10/14 10:21:42 unsupported GOARCH mips
```
I'm assuming the go tools would also arrange for source code to be available as per the import statements - at the moment, main.go fails immediately with
```
[centos filebeat-master]$ gccgo -o lgf `ls *.go`
main.go:4:2: error: import file ‘github.com/elastic/filebeat/beat’ not found
filebeat "github.com/elastic/filebeat/beat"
```
More progress with the logstash-forwarder codebase though.  Pulling out the unwanted darwin/windows, etc .go files has just left me with a handful of (mainly TLS related) compile errors:-
```
[centos@host-192-168-1-12 logstash-forwarder]$ gccgo -o lgf `ls *.go`
publisher1.go:132:29: error: reference to undefined identifier ‘tls.Version’
  tlsconfig.MinVersion = tls.Version.VersionTLS10
                             ^
test.go:1:1: error: expected package ‘main’
 package client
 ^
test.go:33:29: error: reference to undefined identifier ‘tls.VersionTLS10’
  tlsConfig.MinVersion = tls.VersionTLS10
                             ^
fileinfo_linux.go:10:26: error: incompatible type for return value 2 (cannot use type uint32 as type uint64)
   return fstat.Ino, fstat.Dev
                          ^
publisher1.go:132:11: error: reference to undefined field or method ‘MinVersion’
  tlsconfig.MinVersion = tls.Version.VersionTLS10
           ^
test.go:9:13: error: use of undefined type ‘Host’
 func (host *Host) getTLSConfig() (*tls.Config, error) {
             ^
test.go:12:10: error: reference to field ‘TLS’ in object which has no fields or methods
  if !host.TLS {
          ^
test.go:16:38: error: reference to field ‘TLSVerify’ in object which has no fields or methods
  tlsConfig.InsecureSkipVerify = !host.TLSVerify
                                      ^
test.go:18:9: error: reference to field ‘TLSVerify’ in object which has no fields or methods
  if host.TLSVerify {
         ^
test.go:20:36: error: reference to field ‘TLSCaCert’ in object which has no fields or methods
   file, err := ioutil.ReadFile(host.TLSCaCert)
                                    ^
test.go:28:39: error: reference to field ‘TLSCert’ in object which has no fields or methods
  cert, err := tls.LoadX509KeyPair(host.TLSCert, host.TLSKey)
                                       ^
test.go:28:53: error: reference to field ‘TLSKey’ in object which has no fields or methods
  cert, err := tls.LoadX509KeyPair(host.TLSCert, host.TLSKey)
                                                     ^
filecompare.go:12:49: error: incompatible types in binary expression
   return (fstat.Ino == state.Inode && fstat.Dev == state.Device)
                                                 ^
filecompare.go:53:17: error: incompatible types in binary expression
     if stat.Dev == ki.Device && stat.Ino == ki.Inode {
```
Maybe I have incompatibilities between the source code and the build versions of gccgo?
```
gccgo --version
gccgo (centos's mipsel-unknown-linux-gnu GCC phase3 cross-compiler) 4.8.3
```
I'll try a few more build options with filebeat - it's exactly what we're looking for so I'm not giving up just yet :)

**Comment by ruflin** [comment] 2015-10-15 21:57
I add @urso to the discussion as he as more experience with compiler stuff. 
@stevecalvert Let us know if you make some progress.

**Comment by jordansissel** [comment] 2015-11-17 00:40
Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?

**Comment by urso** [comment] 2015-11-17 01:32
Somehow missed this ticket. See follow up discussion on filebeat just linked here.

**Comment by jordansissel** [comment] 2015-11-17 01:33
Thanks @urso! I'll close this in favor of elastic/filebeat#240

**Closed by jordansissel** 2015-11-17 01:33 UTC

**Comment by CharafouddineAhmed** [comment] 2018-07-17 13:10
@ruflin @jordansissel @urso @stevecalvert Bonjour, 

Have you found a solution to this problem?

I am effectively blocked at the same level as @stevecalvert  but I can not find a solution early 4 days. Thank you

**Comment by ruflin** [comment] 2018-07-17 13:40
@CharafouddineAhmed logstash-forwarder is EOL for quite some time now. Please continue this discussion here by opening a topic: https://discuss.elastic.co/c/beats
