### ISSUE TITLE
Failed TLS handshake

### ISSUE THREAD

**Issue by lmorfitt** [elastic/logstash-forwarder#91] opened 2013-09-19 17:41 UTC
Hello,

I suspect this is something dumb but I cant for the life of me figure out why lumberjack has started to throw these errors.

2013/09/19 12:36:37.093618 Failed to tls handshake with 192.168.51.61:5043 read tcp 192.168.51.61:5043: i/o timeout
2013/09/19 12:36:38.093839 Connecting to 192.168.51.61:5043
2013/09/19 12:36:53.094597 Failed to tls handshake with 192.168.51.61:5043 read tcp 192.168.51.61:5043: i/o timeout
2013/09/19 12:36:54.094838 Connecting to 192.168.51.61:5043

We have been using it for a while with no issues, then elastic search ran out of disk space. Cleaned up the disk and now we are seeing these errors.

Restarted logstash, elastic search and the indexer and lumberjack with no update.

thanks
Luke

**Comment by mrteera** [comment] 2015-01-14 06:16
I've this issue too, I still can't figure out how to fix it.

```
Jan 14 06:14:41 localhost :41Z - logstash-forwarder[14906]: 2015/01/14 06:14:41.392072 Failed to tls handshake with - read tcp -:5000: i/o timeout
Jan 14 06:14:42 localhost :42Z - logstash-forwarder[14906]: 2015/01/14 06:14:42.392444 Connecting to -:5000 (-)
```

**Comment by jordansissel** [comment] 2015-01-14 06:25
@driskell partial acks don't solve stalls.

**Comment by jordansissel** [comment] 2015-01-14 06:27
I'm not sure what this ticket is about. 

The original filing was about TLS handshake timeouts. It was later reopened by @yummylogs reporting a different problem (read ack timeout).

@mrteera Your problem reports `read tcp -:5000` and `-` is not a valid hostname, so I don't know what's going on with your system.

Can we close this and open new tickets focused on each kind of error?

**Comment by driskell** [comment] 2015-01-14 13:28
Partial acks solve read ack timeouts and solve event duplication (forwarder resends ALL logs on timeout). If logstash does not push all 1024 spool events (if it's a full spoil) through its pipeline within network timeout of 15 seconds... It will always timeout and resend all 1024. I've seen a logstash continually duplicate logs for hours just because a 100mb log file was added and sent all at once. Brokers alleviate this but if broker gets full too...

I admit I've confused the read ack timeout and TLS handshake timeout in other places though. TLS handshake timeout is unrelated to ack.

I did just recall a stall issue same as @myatu in log courier. I'll raise a ticket for you to look into. It causes failed handshake after a time but restarting logstash fixes it.

**Comment by karthik87** [comment] 2015-01-29 10:09
@jordansissel

I have a strange issue where in my logstash forwarder (as a docker) connects to the logstash server( as a docker too) only when I reboot my instance running the forwarder. Both are running on rackspace cloud. 

When I run the docker first time, i just get the following,
Failure connecting to x.x.x.x dial tcp x.x.x.x:5043: i/o timeout

Then when I issue reboot and again run the same docker its connected and can ship logs smoothly.
But I can restart my production servers this easily. So I am stuck here.

Is it anything related to firewall or iptables?

**Comment by juise** [comment] 2015-02-13 13:24
Please, please, please fix it. The problem about 2 years. It's disgusting!

**Comment by driskell** [comment] 2015-02-13 14:31
@juise Such comments are unhelpful and unwelcome

**Comment by juise** [comment] 2015-02-13 17:57
Just for note, the follow problem:

... Read error looking for ack: read tcp x.x.x.x:xxxx: i/o timeout
... Loading client ssl certificate: /opt/logstash-forwarder/ssl/logstash-forwarder.crt and /opt/logstash-forwarder/ssl/logstash-forwarder.key
... Setting trusted CA from file: /opt/logstash-forwarder/ssl/ca.crt
... Connecting to x.x.x.x:xxxx (x.x.x.x)
... Connected to x.x.x.x

may appear when you are using a Ruby module, by example without try catch blocks and exception occure. In log doesn't appear any message about it. It's very - very bad.

**Comment by jordansissel** [comment] 2015-02-13 17:59
> ... Read error looking for ack: read tcp x.x.x.x:xxxx: i/o timeout

This occurs when downstream server doesn't acknowledge within the defined timeout period.

>  ... Loading client ssl certificate: /opt/logstash-forwarder/ssl/logstash-forwarder.crt and /opt/logstash-forwarder/ssl/logstash-forwarder.key

This is not an error.

> ... Setting trusted CA from file: /opt/logstash-forwarder/ssl/ca.crt

This is not an error

> ... Connecting to x.x.x.x:xxxx (x.x.x.x)

This is not an error

> ... Connected to x.x.x.x

This is not an error.

> may appear when you are using a Ruby module

I'm not sure what this means.

**Comment by juise** [comment] 2015-02-13 18:23
If not an error, why the only one solution to make it work after "not at error" is restart. I can reproduce it without any problems.

It can be problem not on the logstash-forwarder side, but in logstash die.

**Comment by jordansissel** [comment] 2015-02-13 18:38
> is restart

A restart of what? logstash or logstash-forwarder?

**Comment by juise** [comment] 2015-02-13 18:41
The both, restart logstash and logstash-forwarder. The order doesn't matter.

**Comment by jordansissel** [comment] 2015-02-13 18:45
The problem *usually* occurs when logstash is overwhelmed by the load you are giving it with logstash-forwarder, causing the forwarder to give up (i/o timeout) waiting for a response and having it try to connect to another logstash if that can help.

In almost all circumstances, the problem is a due to flow problems in logstash or something downstream of logstash itself (for example, if an output's dependency is down or offline or unavailable).

This ticket is about "Failed TLS handshake" doesn't seem related to the 'Read error looking for ack: read tcp x.x.x.x:xxxx: i/o timeout' message you report.

**Comment by sledorze** [comment] 2015-04-01 10:51
Got this issue without load... (1 req / 10 mins)

**Comment by cameronevans** [comment] 2015-04-01 12:19
@sledorze could it possibly be issues with logstash itself? I have had the issue without load myself and it is usually a result of logstash's state.

**Comment by sledorze** [comment] 2015-04-01 12:20
maybe yes, and what was the fix? (it could be useful for logstash-forwarder
users to know about it)

On Wed, Apr 1, 2015 at 2:19 PM, cameronevans <notifications@github.com>
wrote:

> @sledorze <https://github.com/sledorze> could it possibly be issues with
> logstash itself? I have had the issue without load myself and it is usually
> a result of logstash's state.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash-forwarder/issues/91#issuecomment-88455983>
> .
>



-- 
Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorze
<https://twitter.com/#!/stephaneledorze/status/74020060125077504>

Tel: +33 (0) 6 08  76 70 15

**Comment by cameronevans** [comment] 2015-04-01 12:28
It was a number of reasons, usually plugin errors (usually tcp or elasticsearch) that would cause logstash to halt but have the service just spin it up again. Also, if the forwarder was inhaling a file with a great number of lines it would sometimes fill up the queue and throw this error even though there were not many events at the time. The `--debug` option is useful for these cases though it is a lot of information to pour through.

**Comment by e8-preet** [comment] 2015-05-28 17:41
Thanks @choffee modifying the server.rb fixed my issue :)

**Comment by alexanderilyin** [comment] 2015-06-03 18:47
Faced with this two times in last month. Only restart of `logstash` helps.
```
    2015/06/03 11:02:04.669083 Failed to tls handshake with X.X.X.X read tcp X.X.X.X:5000: connection reset by peer
    2015/06/03 11:02:05.669712 Connecting to [X.X.X.X]:5000 (example.com) 
    2015/06/03 11:02:21.670019 Failed to tls handshake with X.X.X.X read tcp X.X.X.X:5000: i/o timeout
    2015/06/03 11:02:22.670621 Connecting to [X.X.X.X]:5000 (example.com) 

```

**Comment by juise** [comment] 2015-06-03 20:26
Try to modify server.rb as @choffee suggested. This works in all versions, include the latest 1.5. Looks like the elastic folks this problem doesn't interesting

**Comment by alexanderilyin** [comment] 2015-06-23 02:19
@juise still facing sometimes with same problem and have to restart `logstash` to fix it.

**Comment by jordansissel** [comment] 2015-06-23 02:34
We are working on solutions that include better messaging on downstream
failures, and other things.

**Comment by jordansissel** [comment] 2015-07-31 16:56
There's so much discussion on unrelated problems in this ticket, I'm going to close this because I cannot follow it easily. If you are still affected by somethingin this ticket, please open a new ticket and provide whatever details you can. Thanks!

**Closed by jordansissel** 2015-07-31 16:56 UTC
