### ISSUE TITLE
LSF -> Logstash cluster behind ELB loses logs

### ISSUE THREAD

**Issue by tommclaughlan** [elastic/logstash-forwarder#470] opened 2015-06-05 14:03 UTC
I'm having an issue where I am occasionally losing logs when sending from a single LSF instance to a cluster of logstash indexers behind an ELB.

My test set up to reproduce this issue:

A Java application writing a single log line every 100ms, rotating every 8kb. The logs consist of an incrementing counter. The rotation renames the file, ie we start with 'test.log', and rename that 'test.log.1', starting the log again on 'test.log'.
A logstash forwarder instance watching the log file and shipping them to the ELB.
The ELB sends logs to one of a cluster of logstash instances. I start to see this problem as soon as I use 2+ instances.
Logstash then indexes these in elasticsearch.

Observation:

Run the Java app + lsf for a few minutes, which results in a few rotations of the log file. My most recent test reached 1.5k logs.
Grabbing the data from elasticsearch, I notice that log 1401 is missing.

I check the logs on the two logstash instances. One instance indexes up to 1400, then no further. The next instance starts indexing from 1402.

In this example, 1401 is the log immediately before the rotation happens, but I have observed the exact same behaviour on logs in the middle of a log file.

Some logs:

logstash1:

    {
           "message" => "Count : 1397",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:14.614Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "8737",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1398",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:14.614Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "8750",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1399",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:14.614Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "8763",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1400",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:14.615Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "8776",
              "type" => "test",
          "serverid" => "testing2"
    }

logstash2:

    {
           "message" => "Count : 1285",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:35:59.667Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "7281",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1286",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:35:59.667Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "7294",
          "serverid" => "testing2",
              "type" => "test"
    }
    {
           "message" => "Count : 1402",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:22.106Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "0",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1403",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:22.106Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "13",
              "type" => "test",
          "serverid" => "testing2"
    }
    {
           "message" => "Count : 1404",
          "@version" => "1",
        "@timestamp" => "2015-06-05T13:36:22.106Z",
              "file" => "testLog.log",
              "host" => "bulbasaur",
            "offset" => "26",
              "type" => "test",
          "serverid" => "testing2"
    }

The only log missing is 'Count : 1401'. This line exists in the log file.

I can't really figure out why this is happening, and why it happens at different times, in different places in the log.
It doesn't appear to be caused by the rotation, as I still see this behaviour without it.
No logs are lost when I use a single logstash instance behind the ELB, so it sounds like when a connection is lost and it reconnects to a different server, _sometimes_ a log is lost.

My understanding is that this should not happen, that lsf maintains a pointer to it's most recently transmitted log and uses acknowledgment of receipt from the logstash server to ensure lossless log transmission?

If you want me to run some more tests on this, or share test code and config, please let me know.
Thanks,

Tom

Finally, some logs from lsf:

    2015/06/05 14:16:27.309538 Connected to xx.xx.xx.xx
    2015/06/05 14:16:27.429813 Registrar: processing 50 events
    2015/06/05 14:16:34.554615 Read error looking for ack: EOF
    2015/06/05 14:16:34.554681 Setting trusted CA from file: server.crt
    2015/06/05 14:16:34.555998 Connecting to [xx.xx.xx.xx]:443 (logstash.xxx.xxx.com)
    2015/06/05 14:16:34.807821 Connected to xx.xx.xx.xx
    2015/06/05 14:16:34.887845 Registrar: processing 70 events
    2015/06/05 14:16:39.563828 Launching harvester on rotated file: testLog.log
    2015/06/05 14:16:39.563970 harvest: "testLog.log" (offset snapshot:0)
    2015/06/05 14:16:42.052893 Read error looking for ack: EOF
    2015/06/05 14:16:42.052940 Setting trusted CA from file: server.crt
    2015/06/05 14:16:42.054296 Connecting to [xx.xx.xx.xx]:443 (logstash.xxx.xxx.com)
    2015/06/05 14:16:42.304615 Connected to xx.xx.xx.xx
    2015/06/05 14:16:42.386989 Registrar: processing 47 events

**Comment by driskell** [comment] 2015-06-05 14:16
How are you making it disconnect and reconnect?

**Comment by tommclaughlan** [comment] 2015-06-05 14:23
I'm not doing anything intentionally to cause that. A wireshark trace is suggesting that the remote server is sending a FIN to the box running lsf, but I've not put anything in place to close anything.

**Comment by tommclaughlan** [comment] 2015-06-22 13:06
I wonder if there has been progress in investigating this issue?

**Comment by lmorfitt** [comment] 2015-07-02 15:56
@tommclaughlan  I have seen this issue when placing logstash 1.4.2 behind a cisco ace with LSF 0.3.1. 

I figured it was related to the health checks on the ACE card connecting to Logstash. Our solution was to remove the cisco ace and use an array of servers in the LSF config.

IIRC I could reproduce the issue by telnetting to the logstash server, this caused a disconnect of LSF from the logstash server.

**Comment by ph** [comment] 2015-08-19 20:30
It was a problem in the `ruby-lumberjack` library, the windows was incorrectly calculated and was causing unintended acknowledgements, this should be fixed in the latest version of the `logstash-input-lumberjack`. Logstash 1.4.x and 1.5.x are affected by this issue, if you are running logstash 1.5 upgrade the logstash-input-lumberjack plugin.

Ref:  https://github.com/elastic/ruby-lumberjack/pull/9

**Closed by ph** 2015-08-19 20:30 UTC

**Comment by lmorfitt** [comment] 2015-08-24 10:17
@ph thank you for the confirmation of this issue.
