### ISSUE TITLE
Formatting error in the syslog output

### ISSUE THREAD

**Issue by robin13** [elastic/logstash-forwarder#283] opened 2014-10-10 14:10 UTC
I see this in my syslog, and it looks like a formatting error:

Oct 10 16:00:59 apm02 logstash-forwarder[24861]: 2014/10/10 16:00:59.425018 Stopping harvest of /path/to/my/log.json; last change was %!d(float64=86408.685631076) seconds ago

**Comment by jordansissel** [comment] 2015-08-10 18:20
Duplicate of #279, agreed.

**Closed by jordansissel** 2015-08-10 18:20 UTC
