### ISSUE TITLE
Logstash is logging non error events to logstash-forwarder.err

### ISSUE THREAD

**Issue by PSiAU** [elastic/logstash-forwarder#414] opened 2015-03-06 01:42 UTC
Firstly I want to thank @jordansissel for all his hard work bringing the logstash-forwarder repos back online as well as for the new Debian package.
Just a small bug report regarding the new recently released package (0.4.0) of logstash-forwarder. It is logging non error events to logstash-forwarder.err
2015/03/06 12:35:56.178788 Registrar: processing 1024 events

That kind of output should go into logstash-forwarder.log.

Thanks!

**Comment by jordansissel** [comment] 2015-03-06 02:08
You can quiet these with the `-quiet` flag.

**Comment by jordansissel** [comment] 2015-03-06 02:10
This is a duplicate of #408

**Comment by jordansissel** [comment] 2015-03-06 02:10
And #395

**Comment by jordansissel** [comment] 2015-03-15 04:16
Following this in #395

**Closed by jordansissel** 2015-03-15 04:16 UTC
